services:
  lazytainer:
    image: ghcr.io/vmorganp/lazytainer:master
    container_name: lazytainer
    environment:
      VERBOSE: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - lazytainer.group.minecraft.sleepMethod=stop
      - lazytainer.group.minecraft.ports=25565
      - lazytainer.group.minecraft.minPacketThreshold=2 # Start after two incoming packets
      - lazytainer.group.minecraft.inactiveTimeout=600 # 10 minutes
      - lazytainer.group.terraria.sleepMethod=stop
      - lazytainer.group.terraria.ports=7777
      - lazytainer.group.terraria.minPacketThreshold=2 # Start after two incoming packets
      - lazytainer.group.terraria.inactiveTimeout=600 # 10 minutes
      - lazytainer.group.factorio.sleepMethod=stop
      - lazytainer.group.factorio.ports=34197
      - lazytainer.group.factorio.minPacketThreshold=2 # Start after two incoming packets
      - lazytainer.group.factorio.inactiveTimeout=600 # 10 minutes
    restart: unless-stopped
    networks:
      game_net:
        aliases:
          - lazytainer

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    stdin_open: true
    tty: true
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21"
      MEMORY: "3G"
      USE_AIKAR_FLAGS: "TRUE"
      DIFFICULTY: "HARD"
      MAX_PLAYERS: "69"
      SNOOPER_ENABLED: "FALSE"
      STOP_SERVER_ANNOUNCE_DELAY: "30"
    healthcheck:
      test: mc-health
      start_period: 2m
      interval: 1m
      retries: 3
    volumes:
      - ./vanilla-data:/data
    labels:
      - lazytainer.group=minecraft
    depends_on:
      - lazytainer
    networks:
      - game_net
    ports:
      - "25565:25565"
    stop_grace_period: 60s
    restart: unless-stopped

  terraria:
    image: beardedio/terraria:tshock-latest
    container_name: terraria
    stdin_open: true
    tty: true
    environment:
      - world=Niner_Gang.wld
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/v2/server/status"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./terraria-data:/config
    labels:
      - lazytainer.group=terraria
    depends_on:
      - lazytainer
    networks:
      - game_net
    ports:
      - "7777:7777"
    restart: unless-stopped

  factorio:
    image: factoriotools/factorio:stable
    container_name: factorio
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "34197"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./factorio-data/factorio:/factorio
    labels:
      - lazytainer.group=factorio
    depends_on:
      - lazytainer
    networks:
      - game_net
    ports:
      - "34197:34197"
    restart: unless-stopped

networks:
  game_net:
    driver: bridge
