services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    stdin_open: true
    tty: true
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21"
      INIT_MEMORY: 1G
      MAX_MEMORY: 3G
      USE_AIKAR_FLAGS: "TRUE"
      DIFFICULTY: "HARD"
      MAX_PLAYERS: "69"
      SNOOPER_ENABLED: "FALSE"
      STOP_SERVER_ANNOUNCE_DELAY: "30"
    healthcheck:
      test: mc-health
      start_period: 2m
      interval: 1m
      retries: 3
    volumes:
      - ./vanilla-data:/data
    networks:
      - game_net
    ports:
      - "25565:25565"
    stop_grace_period: 60s
    restart: unless-stopped

  terraria:
    image: beardedio/terraria:tshock-latest
    container_name: terraria
    stdin_open: true
    tty: true
    environment:
      - world=Niner_Gang.wld
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878/v2/server/status"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./terraria-data:/config
    networks:
      - game_net
    ports:
      - "7777:7777"
    restart: unless-stopped

  factorio:
    image: factoriotools/factorio:stable
    container_name: factorio
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "34197"]
      interval: 1m
      timeout: 10s
      retries: 3
    volumes:
      - ./factorio-data/factorio:/factorio
    networks:
      - game_net
    ports:
      - "34197:34197"
    restart: unless-stopped

networks:
  game_net:
    driver: bridge